import Head from 'next/head'
import Image from 'next/image'
import {Inter} from 'next/font/google'

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/castle-digital-logo.ico"/>
            </Head>
            <main className={'h-screen bg-zinc-200 flex items-center justify-center flex-col'}>

                <h1 className={'lg:text-6xl text-4xl font-bold mb-3 text-center'}>What Key App</h1>
                <a href="/what_key_v1.apk" className={'lg:text-4xl text-2xl text-zinc-400 hover:text-zinc-700 hover:text-[2.27rem]'}>Mobile App
                    ver1.0</a>

                <p className={'mt-48 text-zinc-400'}>Managed by</p>
                <a href="https://castledigital.com.au/">
                    <Image className={''} src={'/Castle-Digital-Logo.png'} width={200} height={500} />
                </a>
            </main>
        </>
    )
}
